# 最初に実行するファイルのパスを指定する
# src/main/java/...に続くパスと同じ（フォルダ名とファイル名を合わせる）
main: com.example.reboot_plugin.Main
# プラグインの名前（自分で自由に決められる）
name: RebootPlugin
# プラグインのバージョン（自分で自由に決められる）
version: 0.1.2
# 使用するAPIのバージョン（マインクラフトのバージョンと合わせる）
# 「1.18.1」などではなく「1.18」が正しい
api-version: 1.19